name: Deploy to Cloudtype

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3 # 코드 체크아웃

    # Firebase 인증서 설정 (기존 유지)
    - name: Set up Firebase credentials
      run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > serviceAccountKey.json

    # Cloudtype 공식 배포 액션 사용
    - name: Deploy to Cloudtype
      uses: cloudtype-github-actions/deploy@v1
      with:
        token: ${{ secrets.CLOUDTYPE_API_KEY }} # Cloudtype API 키
        project: madksj/nugulmap
        file: ./cloudtype.yml
